export async function GET() {
  const hasOpenAiKey = Boolean(process.env.OPENAI_API_KEY?.trim());

  return Response.json({
    source: hasOpenAiKey ? "openai" : "mock",
    message: hasOpenAiKey
      ? "Responses are generated by OpenAI using your portfolio data."
      : "Responses are local placeholders. Add OPENAI_API_KEY to .env.local for real AI.",
  });
}
